/**
 * Agent Activity Types
 *
 * Types for the unified agent visibility layer.
 * All agent visibility components consume these types through useAgentActivity hook.
 */

// =============================================================================
// Agent Status (Deterministic)
// =============================================================================

export type AgentStatus = 'idle' | 'working' | 'waiting_approval';

// =============================================================================
// Agent Event Types
// =============================================================================

export type AgentEventType =
  // Run lifecycle
  | 'agent.run_started'
  | 'agent.run_completed'
  | 'agent.run_failed'
  // Tool calls
  | 'agent.tool_called'
  | 'agent.tool_completed'
  | 'agent.tool_failed'
  // Deal operations
  | 'deal.created'
  | 'deal.scored'
  | 'deal.analyzed'
  | 'deal.stage_changed'
  // Document operations
  | 'doc.extracted'
  | 'doc.summarized'
  | 'doc.indexed'
  // Communication
  | 'email.drafted'
  | 'email.sent'
  | 'loi.drafted'
  // Approvals
  | 'approval.requested'
  | 'approval.approved'
  | 'approval.rejected';

// =============================================================================
// Agent Activity Response
// =============================================================================

export interface AgentActivityEvent {
  id: string;
  type: AgentEventType;
  label: string; // Human-readable summary
  timestamp: string; // ISO date
  dealId?: string;
  dealName?: string;
  metadata?: Record<string, unknown>;
}

export interface AgentActivityStats {
  toolsCalledToday: number;
  approvalsProcessed: number;
  dealsAnalyzed: number;
  runsCompleted24h: number;
}

export interface AgentLastActivity {
  label: string;
  timestamp: string;
  dealId?: string;
  threadId?: string;
  runId?: string;
}

export interface AgentCurrentRun {
  runId: string;
  threadId: string;
  status: 'running' | 'waiting_approval';
  progressLabel: string;
  startedAt: string;
  dealId?: string;
  dealName?: string;
}

export interface AgentRecentRun {
  runId: string;
  threadId: string;
  status: 'completed' | 'failed' | 'cancelled';
  summary: string;
  startedAt: string;
  completedAt: string;
  dealId?: string;
  dealName?: string;
  toolsCalled: number;
  approvalsRequested: number;
}

export interface AgentActivityResponse {
  // Current status (deterministic rules)
  status: AgentStatus;

  // Last activity summary
  lastActivity: AgentLastActivity | null;

  // Recent activity (summarized events)
  recent: AgentActivityEvent[];

  // Aggregated stats
  stats: AgentActivityStats;

  // Current active run (if any)
  currentRun?: AgentCurrentRun;

  // Recent runs for history view
  recentRuns: AgentRecentRun[];
}

// =============================================================================
// Note: Labels are generated by the backend, not frontend
// =============================================================================

/**
 * Event labels are generated by the backend and included in the response.
 * Frontend components should just display event.label directly.
 * This ensures consistency and allows backend to use full context for label generation.
 */
